const NodeType =  {
  CompilationUnit: "CompilationUnit",
  IfStatement: "IfStatement",
  ForStatement: "ForStatement",
  PostfixExpression: "PostfixExpression",
  PrefixExpression: "PrefixExpression",
  TypeDeclaration: "TypeDeclaration",
  FieldDeclaration: "FieldDeclaration",
  VariableDeclarationFragment: "VariableDeclarationFragment",
  Primitive: "PrimitiveType",
  ExpressionStatement: "ExpressionStatement",
  Assignment: "Assignment",
  FieldAccess: "FieldAccess",
  SimpleName: "SimpleName",
  NumberLiteral: "NumberLiteral",
  ThisExpression: "ThisExpression",
  MethodDeclaration: "MethodDeclaration",
  MethodInvocation: "MethodInvocation",
  Modifier: "Modifier",
  InfixExpression: "InfixExpression",
  LineEmpty: "LineEmpty",
  ReturnStatement: "ReturnStatement",
  Block: "Block",
  TypeDeclarationStatement: "TypeDeclarationStatement",
  SuperConstructorInvocation: "SuperConstructorInvocation",
  VariableDeclarationStatement: "VariableDeclarationStatement",
  VariableDeclarationExpression: "VariableDeclarationExpression",
}

export default NodeType;
